import { IssuerTravelPortalSchema, type IssuerTravelPortal } from './booking';

/**
 * Curated issuer travel portals (MVP). Values are illustrative rule stubs —
 * not live bank T&Cs. Admin CMS can replace this later.
 */
const RAW_PORTALS = [
  {
    id: 'portal_hdfc_smartbuy',
    slug: 'hdfc-smartbuy',
    name: 'HDFC SmartBuy',
    bankSlug: 'hdfc',
    bankName: 'HDFC Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.smartbuy.hdfcbank.com/',
    domains: ['smartbuy.hdfcbank.com', 'hdfcbank.com'],
    deepLinkTemplate:
      'https://www.smartbuy.hdfcbank.com/?product={product}&from={origin}&to={destination}&depart={departureDate}',
    supportedCardHints: ['Regalia', 'Infinia', 'Diners', 'Millennia', 'HDFC'],
    acceleration: {
      multiplier: 10,
      baselineMultiplier: 2,
      pointValueInr: 0.25,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated rewards on eligible SmartBuy flight & hotel bookings',
      eligibilityNotes:
        'Acceleration typically requires booking on SmartBuy with an eligible HDFC card.',
    },
    eligibilityNotes:
      'Reservation completes on HDFC SmartBuy. CardWise only recommends the channel and card.',
  },
  {
    id: 'portal_axis_travel_edge',
    slug: 'axis-travel-edge',
    name: 'Axis Travel Edge',
    bankSlug: 'axis',
    bankName: 'Axis Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.axisbank.com/',
    domains: ['travel.axisbank.com', 'axisbank.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Magnus', 'Ace', 'Atlas', 'Privilege', 'Axis'],
    acceleration: {
      multiplier: 5,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated Edge Rewards on eligible Axis travel portal bookings',
      eligibilityNotes: 'Confirm live portal T&Cs; multipliers vary by card product.',
    },
    eligibilityNotes:
      'Opens Axis Bank travel surface. Complete booking on the bank site to earn portal acceleration.',
  },
  {
    id: 'portal_amex_travel',
    slug: 'amex-travel',
    name: 'Amex Travel',
    bankSlug: 'amex',
    bankName: 'American Express',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.americanexpress.com/en-in/',
    domains: ['amextravel.com', 'americanexpress.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Platinum', 'Gold', 'MRCC', 'Amex', 'Membership'],
    acceleration: {
      multiplier: 5,
      baselineMultiplier: 1,
      pointValueInr: 0.4,
      pointsPerHundredInr: 1,
      category: 'TRAVEL' as const,
      summary: 'Membership Rewards acceleration when booking via Amex Travel',
      eligibilityNotes: 'Eligible Amex cards only; portal earn rates differ from merchant swipes.',
    },
    eligibilityNotes: 'Handoff to American Express India travel experiences.',
  },
  {
    id: 'portal_icici_travel',
    slug: 'icici-travel',
    name: 'ICICI Bank Travel',
    bankSlug: 'icici',
    bankName: 'ICICI Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.icicibank.com/',
    domains: ['icicibank.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Emeralde', 'Sapphiro', 'Rubyx', 'ICICI'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Elevated reward rates on eligible ICICI travel portal bookings',
      eligibilityNotes: 'Acceleration applies only when booked via the bank travel channel.',
    },
    eligibilityNotes: 'Complete the reservation on the ICICI travel experience to qualify.',
  },
  {
    id: 'portal_sbi_travel',
    slug: 'sbi-travel',
    name: 'SBI Card Travel',
    bankSlug: 'sbi',
    bankName: 'SBI Card',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.sbicard.com/',
    domains: ['sbicard.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Prime', 'Elite', 'Pulse', 'SBI'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Bonus reward points on eligible SBI Card travel bookings',
      eligibilityNotes: 'Portal-specific offers may stack; verify on sbicard.com.',
    },
    eligibilityNotes: 'Book on the SBI Card travel channel for accelerated earn.',
  },
  {
    id: 'portal_kotak_travel',
    slug: 'kotak-travel',
    name: 'Kotak Bank Travel',
    bankSlug: 'kotak',
    bankName: 'Kotak Mahindra Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.kotak.com/',
    domains: ['kotak.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['White', 'Zen', 'League', 'Privy', 'Kotak'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Elevated Kotak rewards on eligible bank travel bookings',
      eligibilityNotes: 'Portal acceleration varies by Kotak card product and campaign.',
    },
    eligibilityNotes: 'Complete booking on the Kotak travel channel for accelerated earn.',
  },
  {
    id: 'portal_idfc_first_travel',
    slug: 'idfc-first-travel',
    name: 'IDFC FIRST Travel',
    bankSlug: 'idfc-first',
    bankName: 'IDFC FIRST Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.idfcfirstbank.com/',
    domains: ['idfcfirstbank.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Wealth', 'Select', 'Millennia', 'IDFC', 'FIRST'],
    acceleration: {
      multiplier: 5,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated FIRST rewards on eligible IDFC travel portal bookings',
      eligibilityNotes: 'Confirm card eligibility and live portal rates before booking.',
    },
    eligibilityNotes: 'Handoff to IDFC FIRST Bank travel experiences.',
  },
  {
    id: 'portal_indusind_travel',
    slug: 'indusind-travel',
    name: 'IndusInd Bank Travel',
    bankSlug: 'indusind',
    bankName: 'IndusInd Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.indusind.com/',
    domains: ['indusind.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Legend', 'Pioneer', 'Crest', 'Pinnacle', 'IndusInd'],
    acceleration: {
      multiplier: 5,
      baselineMultiplier: 2,
      pointValueInr: 0.25,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated IndusInd reward points on eligible travel portal bookings',
      eligibilityNotes: 'Premium IndusInd cards often see higher portal multipliers.',
    },
    eligibilityNotes: 'Book on the IndusInd travel channel to qualify for acceleration.',
  },
  {
    id: 'portal_yes_bank_travel',
    slug: 'yes-bank-travel',
    name: 'YES BANK Travel',
    bankSlug: 'yes-bank',
    bankName: 'Yes Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.yesbank.in/',
    domains: ['yesbank.in'],
    deepLinkTemplate: null,
    supportedCardHints: ['Marquee', 'Prosperity', 'Ace', 'YES'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Bonus YES Rewards on eligible bank travel bookings',
      eligibilityNotes: 'Rates depend on live YES BANK card programmes.',
    },
    eligibilityNotes: 'Finish the reservation on the YES BANK travel surface.',
  },
  {
    id: 'portal_sc_travel',
    slug: 'standard-chartered-travel',
    name: 'Standard Chartered Travel',
    bankSlug: 'standard-chartered',
    bankName: 'Standard Chartered',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.sc.com/in/',
    domains: ['sc.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Ultimate', 'Smart', 'Manhattan', 'Standard Chartered', 'SC'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.25,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Elevated SC Rewards on eligible Standard Chartered travel bookings',
      eligibilityNotes: 'Verify portal campaigns; multipliers differ by product.',
    },
    eligibilityNotes: 'Complete booking via Standard Chartered travel channels.',
  },
  {
    id: 'portal_bob_travel',
    slug: 'bob-travel',
    name: 'Bank of Baroda Travel',
    bankSlug: 'bob',
    bankName: 'Bank of Baroda',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.bankofbaroda.in/',
    domains: ['bankofbaroda.in'],
    deepLinkTemplate: null,
    supportedCardHints: ['Eterna', 'Select', 'Premier', 'BoB', 'Baroda'],
    acceleration: {
      multiplier: 3,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Extra BoB reward value on eligible bank travel bookings',
      eligibilityNotes:
        'Acceleration is typically modest vs private-bank portals; confirm live offers.',
    },
    eligibilityNotes: 'Book on Bank of Baroda travel offers to qualify.',
  },
  {
    id: 'portal_rbl_travel',
    slug: 'rbl-travel',
    name: 'RBL Bank Travel',
    bankSlug: 'rbl',
    bankName: 'RBL Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.rblbank.com/',
    domains: ['rblbank.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['Icon', 'World Safari', 'Popcorn', 'RBL'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated RBL Fun+/reward rates on eligible travel portal bookings',
      eligibilityNotes: 'Partner travel channels may apply; check card T&Cs.',
    },
    eligibilityNotes: 'Handoff to RBL Bank travel / partner booking surfaces.',
  },
  {
    id: 'portal_hsbc_travel',
    slug: 'hsbc-travel',
    name: 'HSBC Travel',
    bankSlug: 'hsbc',
    bankName: 'HSBC',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.hsbc.co.in/',
    domains: ['hsbc.co.in'],
    deepLinkTemplate: null,
    supportedCardHints: ['Premier', 'Cashback', 'Visa Platinum', 'HSBC'],
    acceleration: {
      multiplier: 4,
      baselineMultiplier: 2,
      pointValueInr: 0.25,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Elevated HSBC rewards on eligible travel portal bookings',
      eligibilityNotes: 'Premier and selected cards often qualify for higher portal earn.',
    },
    eligibilityNotes: 'Complete the booking on HSBC travel experiences to earn acceleration.',
  },
  {
    id: 'portal_au_travel',
    slug: 'au-travel',
    name: 'AU Bank Travel',
    bankSlug: 'au',
    bankName: 'AU Small Finance Bank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.aubank.in/',
    domains: ['aubank.in'],
    deepLinkTemplate: null,
    supportedCardHints: ['Lit', 'Zenith', 'AU'],
    acceleration: {
      multiplier: 3,
      baselineMultiplier: 2,
      pointValueInr: 0.2,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Bonus AU rewards on eligible bank travel bookings',
      eligibilityNotes: 'Confirm live AU card travel offers before booking.',
    },
    eligibilityNotes: 'Book via AU Bank travel / partner channels to qualify.',
  },
  {
    id: 'portal_citi_travel',
    slug: 'citi-travel',
    name: 'Citi Travel',
    bankSlug: 'citi',
    bankName: 'Citibank',
    kind: 'PORTAL_HANDOFF' as const,
    status: 'ACTIVE' as const,
    products: ['FLIGHT', 'HOTEL'] as const,
    baseUrl: 'https://www.online.citibank.co.in/',
    domains: ['citibank.co.in', 'citi.com'],
    deepLinkTemplate: null,
    supportedCardHints: ['PremierMiles', 'Prestige', 'Rewards', 'Citi'],
    acceleration: {
      multiplier: 5,
      baselineMultiplier: 2,
      pointValueInr: 0.25,
      pointsPerHundredInr: 2,
      category: 'TRAVEL' as const,
      summary: 'Accelerated Citi ThankYou / miles on eligible travel portal bookings',
      eligibilityNotes:
        'Citi India cards may route via partner portals after Axis transition — verify live channel.',
    },
    eligibilityNotes: 'Complete booking on the Citi travel channel for portal acceleration.',
  },
] as const;

export const ISSUER_TRAVEL_PORTALS: IssuerTravelPortal[] = RAW_PORTALS.map((portal) =>
  IssuerTravelPortalSchema.parse(portal),
);

export function listActivePortals(product?: 'FLIGHT' | 'HOTEL'): IssuerTravelPortal[] {
  return ISSUER_TRAVEL_PORTALS.filter(
    (portal) =>
      portal.status === 'ACTIVE' && (product == null || portal.products.includes(product)),
  );
}

/** Alias used by extension / shared consumers. */
export const listActiveIssuerTravelPortals = listActivePortals;

export function findPortalById(id: string): IssuerTravelPortal | undefined {
  return ISSUER_TRAVEL_PORTALS.find((portal) => portal.id === id);
}

export function findPortalBySlug(slug: string): IssuerTravelPortal | undefined {
  return ISSUER_TRAVEL_PORTALS.find((portal) => portal.slug === slug);
}

export function findPortalByHostname(hostname: string): IssuerTravelPortal | undefined {
  const normalized = hostname
    .trim()
    .toLowerCase()
    .replace(/^www\./, '');
  return ISSUER_TRAVEL_PORTALS.find((portal) =>
    portal.domains.some((domain) => normalized === domain || normalized.endsWith(`.${domain}`)),
  );
}
