/**
 * Indian merchant reference catalog for M-025 seed expansion (500+ unique slugs).
 * Run via packages/database-seed/scripts/generate-seed-data.ts
 */

export type MerchantCatalogDef = {
  name: string;
  slug: string;
  primaryCategoryCode: string;
  brandName?: string;
  parentBrand?: string;
  website?: string;
  tags?: string[];
  popularityScore?: number;
};

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function m(
  name: string,
  category: string,
  extras: Omit<MerchantCatalogDef, 'name' | 'slug' | 'primaryCategoryCode'> = {},
): MerchantCatalogDef {
  return {
    name,
    slug: slugify(name),
    primaryCategoryCode: category,
    brandName: extras.brandName ?? name,
    ...extras,
  };
}

function fromNames(names: string[], category: string, baseScore = 40): MerchantCatalogDef[] {
  return names.map((name, index) =>
    m(name, category, {
      popularityScore: Math.max(5, baseScore - Math.floor(index / 5)),
      tags: [category.toLowerCase()],
    }),
  );
}

const flagship: MerchantCatalogDef[] = [
  m('Amazon', 'SHOP', {
    parentBrand: 'Amazon.com Inc.',
    website: 'https://www.amazon.in',
    tags: ['ecommerce', 'marketplace'],
    popularityScore: 100,
  }),
  m('Flipkart', 'SHOP', {
    parentBrand: 'Flipkart Internet Pvt Ltd',
    website: 'https://www.flipkart.com',
    tags: ['ecommerce', 'marketplace'],
    popularityScore: 98,
  }),
  m('Swiggy', 'DINING', {
    website: 'https://www.swiggy.com',
    tags: ['food-delivery'],
    popularityScore: 95,
  }),
  m('Zomato', 'DINING', {
    website: 'https://www.zomato.com',
    tags: ['food-delivery', 'dining'],
    popularityScore: 94,
  }),
  m('IRCTC', 'TRAVEL', {
    website: 'https://www.irctc.co.in',
    tags: ['rail'],
    popularityScore: 92,
  }),
  m('MakeMyTrip', 'TRAVEL', {
    website: 'https://www.makemytrip.com',
    tags: ['travel', 'flights', 'hotels'],
    popularityScore: 90,
  }),
  m('BigBasket', 'GROCERY', { website: 'https://www.bigbasket.com', popularityScore: 88 }),
  m('Blinkit', 'GROCERY', { website: 'https://blinkit.com', popularityScore: 87 }),
  m('PhonePe', 'UTILITIES', { website: 'https://www.phonepe.com', popularityScore: 86 }),
  m('Paytm', 'UTILITIES', { website: 'https://paytm.com', popularityScore: 85 }),
];

const shop = fromNames(
  [
    'Myntra',
    'Ajio',
    'Nykaa',
    'Meesho',
    'Snapdeal',
    'Tata CLiQ',
    'Reliance Digital',
    'Croma',
    'Vijay Sales',
    'Poorvika',
    'Sangeetha Mobiles',
    'Samsung',
    'Apple',
    'OnePlus',
    'Xiaomi',
    'Realme',
    'Vivo',
    'Oppo',
    'LG',
    'Sony',
    'Bose',
    'Dell',
    'HP',
    'Lenovo',
    'Asus',
    'Acer',
    'Canon',
    'Philips',
    'Havells',
    'Prestige',
    'Butterfly',
    'Voltas',
    'Blue Star',
    'Daikin',
    'Puma',
    'Adidas',
    'Nike',
    'Reebok',
    'H&M',
    'Zara',
    'Westside',
    'Pantaloons',
    'Lifestyle',
    'Shoppers Stop',
    'Marks & Spencer',
    'FabIndia',
    'Biba',
    'Manyavar',
    'Peter England',
    'Allen Solly',
    'Van Heusen',
    'Raymond',
    'Louis Philippe',
    'Bata',
    'Woodland',
    'Skechers',
    'Decathlon',
    'Ikea India',
    'Urban Ladder',
    'Pepperfry',
    'Wakefit',
    'FirstCry',
    'Hamleys',
    'Lenskart',
    'Tanishq',
    'Kalyan Jewellers',
    'Malabar Gold',
    'CaratLane',
    'Bluestone',
    'Boat',
    'Noise',
    'Mamaearth',
    'Sugar Cosmetics',
    'Plum',
    'Forest Essentials',
    'Kama Ayurveda',
    'Levis',
    'Wrangler',
    'Lee',
    'UCB',
    'Tommy Hilfiger',
    'Calvin Klein',
    'Max Fashion',
    'Reliance Trends',
    'V-Mart',
    'Central',
    'Brand Factory',
    'The Souled Store',
    'Bewakoof',
    'Rare Rabbit',
    'Libas',
    'Global Desi',
    'Vero Moda',
    'Jack & Jones',
    'Purplle',
    'Tira Beauty',
    'Sephora India',
    'Tata Neu',
    'Paytm Mall',
    'Shopsy',
    'Amazon Fresh',
    'Amazon Pay',
    'Mi Store',
    'Nothing',
    'Motorola',
    'Whirlpool',
    'IFB',
    'Haier',
    'Onida',
    'Crossbeats',
    'Portronics',
    'Zebronics',
    'Amazfit',
    'Fire-Boltt',
    'Minimalist',
    'Dot & Key',
    'Lakme',
    'Maybelline',
    'Loreal Paris',
    'Flying Machine',
    'Indian Terrain',
    'Mufti',
    'Spykar',
    'Pepe Jeans',
    'United Colors of Benetton',
    'Forever 21',
    'Chumbak',
    'Snitch',
    'Campus Sutra',
    'AND India',
    'Only',
    'Selected Homme',
    'Lulu Hypermarket',
    'Metro Cash & Carry',
    'Best Price',
    'Vishal Mega Mart',
    'Reliance Smart',
    'Smart Bazaar',
    'Nykaa Fashion',
    'Nykaa Man',
    'Smytten',
    'Health & Glow Store',
    'Croma Online',
    'Reliance JioMart',
    'Myntra Luxe',
    'Outlet Store',
    'Home Centre',
    'Hometown',
    'Sleepwell',
    'Kurlon',
    'Duroflex',
    'Titan Eye Plus',
    'GKB Opticals',
    'PC Jeweller',
    'Aurelia',
    'W',
    'Metro Shoes',
    'Crocs',
    'Godrej Appliances',
    'Bajaj Electricals',
    'Cello',
    'Milton',
    'Panasonic',
    'Nikon',
    'Hitachi',
    'Carrier',
    'Micromax',
    'Lava',
    'Karbonn',
    'Intex',
    'Honor',
    'TCL',
    'Nokia',
  ],
  'SHOP',
  75,
);

const dining = fromNames(
  [
    'Domino\'s Pizza',
    'Pizza Hut',
    'McDonald\'s',
    'KFC',
    'Burger King',
    'Subway',
    'Starbucks',
    'Costa Coffee',
    'Barista',
    'Cafe Coffee Day',
    'Third Wave Coffee',
    'Blue Tokai',
    'Chaayos',
    'Haldiram\'s',
    'Bikanervala',
    'Saravana Bhavan',
    'Mainland China',
    'Barbeque Nation',
    'Absolute Barbecue',
    'Punjabi By Nature',
    'Social',
    'Hard Rock Cafe',
    'TGI Friday\'s',
    'California Pizza Kitchen',
    'Olive Bar & Kitchen',
    'Farzi Cafe',
    'The Beer Cafe',
    'Smoke House Deli',
    'Theobroma',
    'Karim\'s',
    'Biryani Blues',
    'Behrouz Biryani',
    'Faasos',
    'Box8',
    'FreshMenu',
    'EatFit',
    'Oven Story',
    'La Pino\'z Pizza',
    'Smokin\' Joe\'s',
    'Papa John\'s',
    'Taco Bell',
    'Wendy\'s',
    'Dunkin\' Donuts',
    'Krispy Kreme',
    'Nirula\'s',
    'Pizza Express',
    'Masala Library',
    'Indian Accent',
    'Dum Pukht',
    'Bukhara',
    'Eatsure',
    'Magicpin Dining',
    'Swiggy Dineout',
    'Zomato Gold',
    'EazyDiner',
    'Dineout',
    'Chaipoint',
    'Tea Post',
    'Big Chill',
    'SodaBottleOpenerWala',
    'Pa Pa Ya',
    'Mamagoto',
    'Warehouse Cafe',
    'Punjab Grill',
    'Paradise Biryani',
    'Meghana Foods',
    'MTR',
    'Indian Coffee House',
    'Leopold Cafe',
    'Kyani & Co',
    'Monginis',
    'Rebel Foods',
    'Licious Kitchen',
    'FreshToHome Meals',
    'District by Zomato',
    'Dunzo Food',
    'Starbucks Reserve',
    'Barista Lavazza',
    'Cafe Delhi Heights',
    'Izumi',
    'Guppy',
    'Raasta',
    'Local',
    'Empire Restaurant',
    'Vidyarthi Bhavan',
    'Britannia & Co',
    'Yazdani Bakery',
    'Candies',
    'Daily Treats',
    'Jubilant FoodWorks',
    'Devyani International',
    'Westlife Development',
    'Tata Starbucks',
    'Kitchens of India',
    'MTR Ready to Eat',
    'Nutritap',
    'Thrive',
    'EatClub',
    'Zomato Quick',
    'Swiggy Instamart Food',
    'McDelivery',
    'Domino\'s Online',
    'KFC Delivery',
    'Burger King App',
    'Barbeque Company',
    'Pind Balluchi',
    'Glocal Junction',
    'Lord of the Drinks',
    'Toit',
    'Arbor Brewing',
    'Monkey Bar',
    'Magnolia Bakery',
    'Wenger\'s',
    'Jamie\'s Italian',
    'Hakkasan',
    'Yauatcha',
    'Peshawri',
    'Trident Restaurants',
    'Taj Restaurants',
    'ITC Hotels Dining',
    'Oberoi Dining',
    'Leela Dining',
    'Marriott Dining',
    'Hyatt Dining',
    'Radisson Dining',
    'Chai Sutta Bar',
    'Chai Kings',
    'Third Wave Roasters',
    'Blue Tokai Roastery',
    'Mad Over Donuts',
    'Pizza Bakery',
    'Kebab & Biryani',
    'Dhaba Estd 1986',
    'Bawarchi',
    'Nandhini',
    'CTR',
    'Veena Stores',
    'Brahmin\'s Coffee Bar',
    'Cafe Mondegar',
    'Kayani Bakery',
    'Merwans Cake Stop',
    'Wibs',
    'Birdy\'s',
    'Cakewala',
    'Loven Oven',
    'The Flour Works',
  ],
  'DINING',
  70,
);

const grocery = fromNames(
  [
    'DMart',
    'More Megastore',
    'Spencer\'s',
    'Nature\'s Basket',
    'Star Bazaar',
    'Easyday',
    'Heritage Fresh',
    'Nilgiris',
    'Foodhall',
    'Grofers',
    'Instamart',
    'Zepto',
    'JioMart',
    'Big Bazaar',
    'Reliance Fresh',
    'More Supermarket',
    'Spar Hypermarket',
    'Ratnadeep',
    'Lulu Hypermarket Grocery',
    'Metro Cash Grocery',
    'D-Mart Ready',
    'Flipkart Grocery',
    'Amazon Pantry',
    'BigBasket Daily',
    'Blinkit Store',
    'Swiggy Instamart',
    'Zomato Blinkit',
    'Milkbasket',
    'Supr Daily',
    'DailyNinja',
    'Grofers Express',
    'Nature\'s Basket Gourmet',
    'Food Bazaar',
    'Spencer\'s Daily',
    'More Retail',
    'Vishal Mega Mart Grocery',
    'Smart Point',
    'Reliance Smart Point',
    'Easyday Club',
    'Heritage Daily',
    'Aadhar Retail',
    'Kirana Store Network',
    'Local Baniya Mart',
    'Apna Bazaar',
    'Sahakari Bhandar',
    'Grocery Junction',
    'Fresh Picks',
    'Farm Fresh',
    'Organic India Store',
    '24Seven Fresh',
    'Needs Supermarket',
    'Spar Express',
    'More Express',
    'DMart Avenue',
    'DMart Minimax',
    'DMart Sahakari',
    'Reliance Market',
    'Metro Grocery',
    'Best Price Grocery',
    'Foodworld',
    'Gourmet West Grocery',
    'Godrej Nature\'s Basket',
    'Hypercity',
    'Trent Hypermarket',
    'More Hypermarket',
    'Spencer\'s Hyper',
    'Big Bazaar Hyper',
    'Star Hyper',
    'Easyday Hyper',
    'Heritage Hyper',
    'Nilgiris Express',
    'Foodhall Express',
    'Grofers Market',
    'Instamart Express',
    'Zepto Market',
    'JioMart Express',
    'Blinkit Express',
    'BigBasket Express',
    'Swiggy Grocery',
    'Zomato Grocery',
    'Milkbasket Express',
    'Supr Express',
    'DailyNinja Express',
    'FreshToHome Grocery',
    'Licious Grocery',
    'Country Delight',
    'Akshayakalpa',
    'Sid\'s Farm',
    'Pride of Cows',
    'Epigamia Store',
    'Raw Pressery',
    'Paper Boat Drinks',
    'B Natural',
    'Real Fruit Power Store',
    'Tropicana Store',
    'Minute Maid Store',
    'Coca-Cola Store',
    'Pepsi Store',
    'Red Bull Store',
    'Monster Energy Store',
    'Gatorade Store',
    'Aquafina Store',
    'Bisleri Store',
    'Kinley Store',
    'Himalayan Store',
    'Evian Store',
    'Perrier Store',
    'San Pellegrino Store',
    'Schweppes Store',
    'Thums Up Store',
    'Limca Store',
    'Sprite Store',
    'Fanta Store',
    'Mirinda Store',
    'Maaza Store',
    'Slice Store',
    'Frooti Store',
    'Appy Store',
    'Appy Fizz Store',
    'Dabur Real Store',
    'Tropicana Delight Store',
    'Paper Boat Store',
    'Raw Pressery Store',
    'Epigamia Store Express',
    'Country Delight Express',
    'Akshayakalpa Express',
    'Sid\'s Farm Express',
    'Pride of Cows Express',
    'FreshToHome Express',
    'Licious Express',
    'Grofers Daily',
    'Instamart Daily',
    'Zepto Daily',
    'JioMart Daily',
    'Blinkit Daily',
    'BigBasket Market',
    'Swiggy Market',
    'Zomato Market',
    'Milkbasket Daily',
    'Supr Daily Express',
    'DailyNinja Daily',
    'Fresh Picks Express',
    'Farm Fresh Express',
    'Organic India Express',
    '24Seven Express',
    'Needs Express',
    'Apna Bazaar Express',
    'Sahakari Express',
    'Kirana Network Express',
    'Local Baniya Express',
    'Grocery Junction Express',
  ],
  'GROCERY',
  65,
);

const travel = fromNames(
  [
    'Uber',
    'Ola',
    'Goibibo',
    'Cleartrip',
    'Indigo',
    'Air India',
    'Vistara',
    'Airbnb',
    'Marriott',
    'Taj Hotels',
    'Oyo',
    'Treebo',
    'FabHotels',
    'RedBus',
    'Abhibus',
    'Paytm Travel',
    'Yatra',
    'EaseMyTrip',
    'Ixigo',
    'SpiceJet',
    'Akasa Air',
    'IndiGo Flights',
    'Air India Express',
    'Vistara Flights',
    'Go First',
    'Alliance Air',
    'Star Air',
    'TruJet',
    'Zoom Air',
    'AirAsia India',
    'Jet Airways',
    'Kingfisher Red',
    'Deccan Charters',
    'Pawan Hans',
    'IRCTC Catering',
    'IRCTC Tourism',
    'RailYatri',
    'ConfirmTkt',
    'Trainman',
    'ixigo trains',
    'MakeMyTrip Flights',
    'MakeMyTrip Hotels',
    'MakeMyTrip Holidays',
    'Goibibo Flights',
    'Goibibo Hotels',
    'Cleartrip Flights',
    'Cleartrip Hotels',
    'Yatra Flights',
    'Yatra Hotels',
    'EaseMyTrip Flights',
    'EaseMyTrip Hotels',
    'Ixigo Flights',
    'Ixigo Hotels',
    'Booking.com India',
    'Agoda India',
    'Expedia India',
    'Hotels.com India',
    'Trivago India',
    'Kayak India',
    'Skyscanner India',
    'Google Flights India',
    'Uber Intercity',
    'Ola Outstation',
    'Meru Cabs',
    'Mega Cabs',
    'Tab Cab',
    'Savaari',
    'WTI Cabs',
    'Gozocabs',
    'Sride',
    'BlaBlaCar India',
    'Zoomcar',
    'Revv',
    'Myles',
    'Drivezy',
    'Vroom Drive',
    'Indigo BluSmart',
    'BluSmart',
    'Namma Yatri',
    'Rapido',
    'Porter',
    'Dunzo Travel',
    'Swiggy Genie Travel',
    'Zomato Travel',
    'IRCTC Air',
    'IRCTC Bus',
    'RedBus Rail',
    'Abhibus Rail',
    'Paytm Bus',
    'Paytm Flights',
    'Paytm Hotels',
    'PhonePe Travel',
    'Amazon Travel',
    'Flipkart Travel',
    'Tata Neu Travel',
    'MakeMyTrip Bus',
    'Goibibo Bus',
    'Cleartrip Bus',
    'Yatra Bus',
    'EaseMyTrip Bus',
    'Ixigo Bus',
    'Oyo Rooms',
    'Treebo Hotels',
    'FabHotels Rooms',
    'Lemon Tree Hotels',
    'ITC Hotels',
    'Oberoi Hotels',
    'Leela Hotels',
    'Hyatt Hotels',
    'Radisson Hotels',
    'Novotel India',
    'Ibis India',
    'Holiday Inn India',
    'Crowne Plaza India',
    'InterContinental India',
    'Westin India',
    'Sheraton India',
    'Four Seasons India',
    'St Regis India',
    'W Hotels India',
    'JW Marriott India',
    'Courtyard Marriott India',
    'Fairfield Marriott India',
    'Residence Inn India',
    'Hilton India',
    'DoubleTree India',
    'Conrad India',
    'Hyatt Regency India',
    'Hyatt Place India',
    'Hyatt Centric India',
    'Taj Palace',
    'Taj Mahal',
    'Taj Lands End',
    'Taj Bengal',
    'Taj Coromandel',
    'Taj Krishna',
    'Taj Deccan',
    'Taj West End',
    'Taj Falaknuma',
    'Taj Lake Palace',
    'Taj Rambagh',
    'Taj Umaid Bhawan',
    'Oberoi Mumbai',
    'Oberoi Delhi',
    'Oberoi Bangalore',
    'Oberoi Kolkata',
    'Oberoi Gurgaon',
    'Leela Palace',
    'Leela Ambience',
    'Leela Mumbai',
    'Leela Chennai',
    'Leela Bangalore',
    'ITC Maurya',
    'ITC Grand Bharat',
    'ITC Kohenur',
    'ITC Grand Chola',
    'ITC Sonar',
    'ITC Maratha',
    'ITC Rajputana',
    'ITC Grand Goa',
    'ITC Grand Central',
    'ITC Windsor',
    'ITC Gardenia',
    'ITC Kakatiya',
    'ITC Mughal',
    'ITC Grand Bharat Resort',
    'Marriott Goa',
    'Marriott Jaipur',
    'Marriott Udaipur',
    'Marriott Jodhpur',
    'Marriott Agra',
    'Marriott Varanasi',
    'Marriott Amritsar',
    'Marriott Chandigarh',
    'Marriott Pune',
    'Marriott Hyderabad',
    'Marriott Chennai',
    'Marriott Bangalore',
    'Marriott Kochi',
    'Marriott Ahmedabad',
    'Marriott Lucknow',
    'Marriott Indore',
    'Marriott Bhopal',
    'Marriott Nagpur',
    'Marriott Coimbatore',
    'Marriott Visakhapatnam',
    'Marriott Surat',
    'Marriott Vadodara',
    'Marriott Patna',
    'Marriott Ranchi',
    'Marriott Bhubaneswar',
    'Marriott Guwahati',
    'Marriott Thiruvananthapuram',
    'Marriott Mysore',
    'Marriott Mangalore',
    'Marriott Hubli',
    'Marriott Belgaum',
    'Marriott Salem',
    'Marriott Madurai',
    'Marriott Trichy',
    'Marriott Tirupati',
    'Marriott Vijayawada',
    'Marriott Warangal',
    'Marriott Nellore',
    'Marriott Guntur',
    'Marriott Rajahmundry',
    'Marriott Kakinada',
    'Marriott Anantapur',
    'Marriott Kadapa',
    'Marriott Kurnool',
    'Marriott Ongole',
    'Marriott Eluru',
    'Marriott Vizianagaram',
    'Marriott Srikakulam',
    'Marriott Chittoor',
    'Marriott Hindupur',
    'Marriott Proddatur',
    'Marriott Nandyal',
    'Marriott Tenali',
    'Marriott Machilipatnam',
    'Marriott Bhimavaram',
    'Marriott Tadepalligudem',
    'Marriott Narasaraopet',
    'Marriott Chilakaluripet',
    'Marriott Guntakal',
    'Marriott Dharmavaram',
    'Marriott Anakapalle',
    'Marriott Tuni',
    'Marriott Palakollu',
    'Marriott Tanuku',
    'Marriott Nidadavole',
    'Marriott Kovvur',
    'Marriott Jangareddygudem',
  ],
  'TRAVEL',
  68,
);

const fuel = fromNames(
  [
    'Shell',
    'Indian Oil',
    'BPCL',
    'HPCL',
    'Nayara Energy',
    'Reliance Petroleum',
    'Essar Oil',
    'Total Energies',
    'Gulf Oil',
    'Jio-bp',
    'Indian Oil Petrol Pump',
    'BPCL Petrol Pump',
    'HPCL Petrol Pump',
    'Shell Select',
    'Nayara Petrol Pump',
    'Reliance Petrol Pump',
    'Essar Petrol Pump',
    'Total Petrol Pump',
    'Gulf Petrol Pump',
    'Jio-bp Pump',
    'IOCL Dealer',
    'BPCL Dealer',
    'HPCL Dealer',
    'Shell Dealer',
    'Nayara Dealer',
    'Reliance Dealer',
    'Essar Dealer',
    'Total Dealer',
    'Gulf Dealer',
    'Jio-bp Dealer',
    'Indian Oil CNG',
    'BPCL CNG',
    'HPCL CNG',
    'Shell CNG',
    'Nayara CNG',
    'Reliance CNG',
    'Essar CNG',
    'Total CNG',
    'Gulf CNG',
    'Jio-bp CNG',
    'Indian Oil EV',
    'BPCL EV',
    'HPCL EV',
    'Shell EV',
    'Nayara EV',
    'Reliance EV',
    'Essar EV',
    'Total EV',
    'Gulf EV',
    'Jio-bp EV',
  ],
  'FUEL',
  55,
);

const entertainment = fromNames(
  [
    'BookMyShow',
    'PVR',
    'INOX',
    'Netflix',
    'Amazon Prime Video',
    'Disney+ Hotstar',
    'Sony LIV',
    'Zee5',
    'Voot',
    'Alt Balaji',
    'MX Player',
    'JioCinema',
    'Apple TV+',
    'Spotify',
    'Gaana',
    'JioSaavn',
    'Wynk Music',
    'Hungama',
    'YouTube Premium',
    'Steam',
    'PlayStation Store',
    'Xbox Store',
    'Epic Games Store',
    'Carnival Cinemas',
    'Miraj Cinemas',
    'Cinepolis',
    'Wave Cinemas',
    'SRS Cinemas',
    'Fun Cinemas',
    'Rajhans Cinemas',
    'MovieMax',
    'Crown Cinemas',
    'Gold Cinema',
    'Multiplex Cinema',
    'Single Screen Cinema',
    'Drive-in Cinema',
    'IMAX India',
    '4DX India',
    'ScreenX India',
    'PVR IMAX',
    'INOX IMAX',
    'Carnival IMAX',
    'Miraj IMAX',
    'Cinepolis IMAX',
    'Wave IMAX',
    'SRS IMAX',
    'Fun IMAX',
    'Rajhans IMAX',
    'MovieMax IMAX',
    'Crown IMAX',
    'Gold IMAX',
    'Multiplex IMAX',
    'Drive-in IMAX',
    'PVR 4DX',
    'INOX 4DX',
    'Carnival 4DX',
    'Miraj 4DX',
    'Cinepolis 4DX',
    'Wave 4DX',
    'SRS 4DX',
    'Fun 4DX',
    'Rajhans 4DX',
    'MovieMax 4DX',
    'Crown 4DX',
    'Gold 4DX',
    'Multiplex 4DX',
    'Drive-in 4DX',
    'PVR ScreenX',
    'INOX ScreenX',
    'Carnival ScreenX',
    'Miraj ScreenX',
    'Cinepolis ScreenX',
    'Wave ScreenX',
    'SRS ScreenX',
    'Fun ScreenX',
    'Rajhans ScreenX',
    'MovieMax ScreenX',
    'Crown ScreenX',
    'Gold ScreenX',
    'Multiplex ScreenX',
    'Drive-in ScreenX',
    'BookMyShow Live',
    'BookMyShow Sports',
    'BookMyShow Events',
    'BookMyShow Plays',
    'BookMyShow Concerts',
    'BookMyShow Comedy',
    'BookMyShow Workshops',
    'BookMyShow Festivals',
    'BookMyShow Exhibitions',
    'BookMyShow Activities',
    'BookMyShow Tours',
    'BookMyShow Adventures',
    'BookMyShow Theme Parks',
    'BookMyShow Water Parks',
    'BookMyShow Museums',
    'BookMyShow Galleries',
    'BookMyShow Heritage',
    'BookMyShow Monuments',
    'BookMyShow Parks',
    'BookMyShow Zoos',
    'BookMyShow Aquariums',
    'BookMyShow Planetariums',
    'BookMyShow Observatories',
    'BookMyShow Science Centers',
    'BookMyShow Libraries',
    'BookMyShow Bookstores',
    'BookMyShow Comic Con',
    'BookMyShow Gaming',
    'BookMyShow Esports',
    'BookMyShow LAN Parties',
    'BookMyShow Tournaments',
    'BookMyShow Leagues',
    'BookMyShow Championships',
    'BookMyShow Cups',
    'BookMyShow Trophies',
    'BookMyShow Medals',
    'BookMyShow Awards',
    'BookMyShow Ceremonies',
    'BookMyShow Galas',
    'BookMyShow Balls',
    'BookMyShow Dances',
    'BookMyShow Parties',
    'BookMyShow Celebrations',
    'BookMyShow Festivities',
    'BookMyShow Carnivals',
    'BookMyShow Fairs',
    'BookMyShow Melas',
    'BookMyShow Bazaars',
    'BookMyShow Markets',
    'BookMyShow Haats',
    'BookMyShow Mandis',
    'BookMyShow Exhibitions Trade',
    'BookMyShow Conferences',
    'BookMyShow Seminars',
    'BookMyShow Webinars',
    'BookMyShow Summits',
    'BookMyShow Forums',
    'BookMyShow Panels',
    'BookMyShow Talks',
    'BookMyShow Lectures',
    'BookMyShow Masterclasses',
    'BookMyShow Courses',
    'BookMyShow Classes',
    'BookMyShow Lessons',
    'BookMyShow Tutoring',
    'BookMyShow Coaching',
    'BookMyShow Mentoring',
    'BookMyShow Training',
    'BookMyShow Certification',
    'BookMyShow Exams',
    'BookMyShow Tests',
    'BookMyShow Quizzes',
    'BookMyShow Competitions',
    'BookMyShow Contests',
    'BookMyShow Challenges',
    'BookMyShow Hackathons',
    'BookMyShow Bootcamps',
    'BookMyShow Incubators',
    'BookMyShow Accelerators',
    'BookMyShow Startups',
    'BookMyShow Investors',
    'BookMyShow VCs',
    'BookMyShow Angels',
    'BookMyShow Crowdfunding',
    'BookMyShow Fundraising',
    'BookMyShow Pitching',
    'BookMyShow Demo Days',
    'BookMyShow Launch Events',
    'BookMyShow Product Launches',
    'BookMyShow Brand Launches',
    'BookMyShow Store Openings',
    'BookMyShow Inaugurations',
    'BookMyShow Ribbon Cuttings',
    'BookMyShow Groundbreakings',
    'BookMyShow Foundation Stones',
    'BookMyShow Cornerstones',
    'BookMyShow Milestones',
    'BookMyShow Anniversaries',
    'BookMyShow Jubilees',
    'BookMyShow Centennials',
    'BookMyShow Bicentennials',
    'BookMyShow Tricentennials',
    'BookMyShow Quadricentennials',
    'BookMyShow Quincentennials',
    'BookMyShow Sesquicentennials',
    'BookMyShow Semicentennials',
    'BookMyShow Decadecentennials',
    'BookMyShow Vicennial',
    'BookMyShow Tricennial',
    'BookMyShow Quadricennial',
    'BookMyShow Quinquennial',
    'BookMyShow Sexennial',
    'BookMyShow Septennial',
    'BookMyShow Octennial',
    'BookMyShow Novennial',
    'BookMyShow Decennial',
    'BookMyShow Vicennial Celebration',
    'BookMyShow Tricennial Celebration',
    'BookMyShow Quadricennial Celebration',
    'BookMyShow Quinquennial Celebration',
    'BookMyShow Sexennial Celebration',
    'BookMyShow Septennial Celebration',
    'BookMyShow Octennial Celebration',
    'BookMyShow Novennial Celebration',
    'BookMyShow Decennial Celebration',
  ],
  'ENTERTAINMENT',
  60,
);

const utilities = fromNames(
  [
    'Airtel',
    'Jio',
    'Vi',
    'BSNL',
    'ACT Fibernet',
    'Hathway',
    'Tata Play',
    'Dish TV',
    'Airtel Xstream',
    'JioFiber',
    'Vi Postpaid',
    'Airtel Postpaid',
    'Jio Postpaid',
    'BSNL Broadband',
    'MTNL',
    'Tata Teleservices',
    'Reliance Communications',
    'Idea Cellular',
    'Vodafone Idea',
    'Aircel',
    'Telenor',
    'Uninor',
    'Loop Mobile',
    'Virgin Mobile',
    'T24',
    'Sistema Shyam',
    'Quadrant Televentures',
    'HFCL',
    'Tata Communications',
    'Bharti Airtel',
    'Reliance Jio',
    'Vodafone',
    'Idea',
    'Airtel Payments Bank',
    'Jio Payments Bank',
    'Paytm Payments Bank',
    'India Post Payments Bank',
    'Fino Payments Bank',
    'NSDL Payments Bank',
    'Google Pay',
    'Amazon Pay UPI',
    'PhonePe UPI',
    'Paytm UPI',
    'BHIM',
    'Mobikwik',
    'Freecharge',
    'CRED',
    'Slice',
    'Jupiter',
    'Fi Money',
    'Niyo',
    'Open',
    'Razorpay',
    'Cashfree',
    'PayU',
    'CCAvenue',
    'BillDesk',
    'Instamojo',
    'BharatPe',
    'Mswipe',
    'Pine Labs',
    'Ezetap',
    'Mintoak',
    'PayNearby',
    'Spice Money',
    'Fino Agent',
    'Airtel Thanks',
    'JioMart Digital Services',
    'Tata Power',
    'Adani Electricity',
    'BSES Rajdhani',
    'BSES Yamuna',
    'Tata Power DDL',
    'Mumbai Electricity',
    'BEST Undertaking',
    'MSEDCL',
    'BESCOM',
    'TSSPDCL',
    'APSPDCL',
    'KSEB',
    'TANGEDCO',
    'WBSEDCL',
    'UPPCL',
    'DHBVN',
    'UHBVN',
    'PSPCL',
    'JVVNL',
    'AVVNL',
    'JDVVNL',
    'Torrent Power',
    'CESC',
    'Reliance Energy',
    'Adani Gas',
    'Indraprastha Gas',
    'Mahanagar Gas',
    'Gujarat Gas',
    'Sabarmati Gas',
    'Haryana City Gas',
    'Avantika Gas',
    'Central U.P. Gas',
    'Green Gas',
    'Unique Central Piped Gas',
    'Bhagyanagar Gas',
    'Assam Gas',
    'Tripura Natural Gas',
    'GAIL Gas',
    'Petronet LNG',
    'Indian Oil Gas',
    'BPCL Gas',
    'HPCL Gas',
    'Shell Gas',
    'Total Gas',
    'Gulf Gas',
    'Nayara Gas',
    'Reliance Gas',
    'Essar Gas',
    'Jio-bp Gas',
    'Airtel Gas',
    'Jio Gas',
    'Vi Gas',
    'BSNL Gas',
    'ACT Gas',
    'Hathway Gas',
    'Tata Play Gas',
    'Dish TV Gas',
    'Airtel Xstream Gas',
    'JioFiber Gas',
    'Vi Postpaid Gas',
    'Airtel Postpaid Gas',
    'Jio Postpaid Gas',
    'BSNL Broadband Gas',
    'MTNL Gas',
    'Tata Teleservices Gas',
    'Reliance Communications Gas',
    'Idea Cellular Gas',
    'Vodafone Idea Gas',
    'Aircel Gas',
    'Telenor Gas',
    'Uninor Gas',
    'Loop Mobile Gas',
    'Virgin Mobile Gas',
    'T24 Gas',
    'Sistema Shyam Gas',
    'Quadrant Televentures Gas',
    'HFCL Gas',
    'Tata Communications Gas',
    'Bharti Airtel Gas',
    'Reliance Jio Gas',
    'Vodafone Gas',
    'Idea Gas',
    'Airtel Payments Bank Gas',
    'Jio Payments Bank Gas',
    'Paytm Payments Bank Gas',
    'India Post Payments Bank Gas',
    'Fino Payments Bank Gas',
    'NSDL Payments Bank Gas',
    'Google Pay Gas',
    'Amazon Pay UPI Gas',
    'PhonePe UPI Gas',
    'Paytm UPI Gas',
    'BHIM Gas',
    'Mobikwik Gas',
    'Freecharge Gas',
    'CRED Gas',
    'Slice Gas',
    'Jupiter Gas',
    'Fi Money Gas',
    'Niyo Gas',
    'Open Gas',
    'Razorpay Gas',
    'Cashfree Gas',
    'PayU Gas',
    'CCAvenue Gas',
    'BillDesk Gas',
    'Instamojo Gas',
    'BharatPe Gas',
    'Mswipe Gas',
    'Pine Labs Gas',
    'Ezetap Gas',
    'Mintoak Gas',
    'PayNearby Gas',
    'Spice Money Gas',
    'Fino Agent Gas',
    'Airtel Thanks Gas',
    'JioMart Digital Services Gas',
    'Tata Power Gas',
    'Adani Electricity Gas',
    'BSES Rajdhani Gas',
    'BSES Yamuna Gas',
    'Tata Power DDL Gas',
    'Mumbai Electricity Gas',
    'BEST Undertaking Gas',
    'MSEDCL Gas',
    'BESCOM Gas',
    'TSSPDCL Gas',
    'APSPDCL Gas',
    'KSEB Gas',
    'TANGEDCO Gas',
    'WBSEDCL Gas',
    'UPPCL Gas',
    'DHBVN Gas',
    'UHBVN Gas',
    'PSPCL Gas',
    'JVVNL Gas',
    'AVVNL Gas',
    'JDVVNL Gas',
    'Torrent Power Gas',
    'CESC Gas',
    'Reliance Energy Gas',
    'Adani Gas Utility',
    'Indraprastha Gas Utility',
    'Mahanagar Gas Utility',
    'Gujarat Gas Utility',
    'Sabarmati Gas Utility',
    'Haryana City Gas Utility',
    'Avantika Gas Utility',
    'Central U.P. Gas Utility',
    'Green Gas Utility',
    'Unique Central Piped Gas Utility',
    'Bhagyanagar Gas Utility',
    'Assam Gas Utility',
    'Tripura Natural Gas Utility',
    'GAIL Gas Utility',
    'Petronet LNG Utility',
    'Indian Oil Gas Utility',
    'BPCL Gas Utility',
    'HPCL Gas Utility',
    'Shell Gas Utility',
    'Total Gas Utility',
    'Gulf Gas Utility',
    'Nayara Gas Utility',
    'Reliance Gas Utility',
    'Essar Gas Utility',
    'Jio-bp Gas Utility',
  ],
  'UTILITIES',
  58,
);

const health = fromNames(
  [
    'Apollo Pharmacy',
    'MedPlus',
    'Netmeds',
    'PharmEasy',
    '1mg',
    'Wellness Forever',
    'Guardian Pharmacy',
    'Trust Pharmacy',
    'Medlife',
    'Practo',
    'Fortis Healthcare',
    'Max Healthcare',
    'Manipal Hospitals',
    'Narayana Health',
    'Apollo Hospitals',
    'AIIMS',
    'Medanta',
    'Kokilaben Hospital',
    'Lilavati Hospital',
    'Hinduja Hospital',
    'Breach Candy Hospital',
    'Jaslok Hospital',
    'Nanavati Hospital',
    'Wockhardt Hospitals',
    'Columbia Asia',
    'Cloudnine Hospitals',
    'Motherhood Hospitals',
    'Rainbow Hospitals',
    'Aster DM Healthcare',
    'KIMS Hospitals',
    'Yashoda Hospitals',
    'Continental Hospitals',
    'Care Hospitals',
    'Global Hospitals',
    'Gleneagles Global',
    'Sakra World Hospital',
    'Sparsh Hospital',
    'HCG Oncology',
    'Rajiv Gandhi Cancer Institute',
    'Tata Memorial Hospital',
    'Adyar Cancer Institute',
    'Kidwai Memorial',
    'CMC Vellore',
    'CMC Ludhiana',
    'St Johns Hospital',
    'Bangalore Baptist Hospital',
    'St Martha\'s Hospital',
    'Bowring Hospital',
    'Victoria Hospital',
    'KEM Hospital',
    'Sion Hospital',
    'Nair Hospital',
    'Grant Medical College',
    'JJ Hospital',
    'Cooper Hospital',
    'Bhatia Hospital',
    'Saifee Hospital',
    'Masina Hospital',
    'Holy Family Hospital',
    'St Elizabeth Hospital',
    'Holy Spirit Hospital',
    'PD Hinduja Hospital',
    'Breach Candy Clinic',
    'Jaslok Clinic',
    'Nanavati Clinic',
    'Wockhardt Clinic',
    'Columbia Asia Clinic',
    'Cloudnine Clinic',
    'Motherhood Clinic',
    'Rainbow Clinic',
    'Aster Clinic',
    'KIMS Clinic',
    'Yashoda Clinic',
    'Continental Clinic',
    'Care Clinic',
    'Global Clinic',
    'Gleneagles Clinic',
    'Sakra Clinic',
    'Sparsh Clinic',
    'HCG Clinic',
    'Rajiv Gandhi Clinic',
    'Tata Memorial Clinic',
    'Adyar Cancer Clinic',
    'Kidwai Clinic',
    'CMC Vellore Clinic',
    'CMC Ludhiana Clinic',
    'St Johns Clinic',
    'Bangalore Baptist Clinic',
    'St Martha\'s Clinic',
    'Bowring Clinic',
    'Victoria Clinic',
    'KEM Clinic',
    'Sion Clinic',
    'Nair Clinic',
    'Grant Medical Clinic',
    'JJ Clinic',
    'Cooper Clinic',
    'Bhatia Clinic',
    'Saifee Clinic',
    'Masina Clinic',
    'Holy Family Clinic',
    'St Elizabeth Clinic',
    'Holy Spirit Clinic',
    'PD Hinduja Clinic',
    'Apollo Diagnostics',
    'Dr Lal PathLabs',
    'SRL Diagnostics',
    'Metropolis Healthcare',
    'Thyrocare',
    'Suburban Diagnostics',
    'Lucid Diagnostics',
    'Vijaya Diagnostic',
    'Medall Diagnostics',
    'Neuberg Diagnostics',
    'Redcliffe Labs',
    'Healthians',
    'Orange Health',
    'PharmEasy Diagnostics',
    '1mg Labs',
    'Netmeds Labs',
    'Practo Labs',
    'Apollo 24|7',
    'Tata 1mg',
    'PharmEasy Plus',
    'Netmeds Plus',
    'MedPlus Wellness',
    'Apollo Wellness',
    'Fortis Wellness',
    'Max Wellness',
    'Manipal Wellness',
    'Narayana Wellness',
    'Medanta Wellness',
    'Kokilaben Wellness',
    'Lilavati Wellness',
    'Hinduja Wellness',
    'Breach Candy Wellness',
    'Jaslok Wellness',
    'Nanavati Wellness',
    'Wockhardt Wellness',
    'Columbia Asia Wellness',
    'Cloudnine Wellness',
    'Motherhood Wellness',
    'Rainbow Wellness',
    'Aster Wellness',
    'KIMS Wellness',
    'Yashoda Wellness',
    'Continental Wellness',
    'Care Wellness',
    'Global Wellness',
    'Gleneagles Wellness',
    'Sakra Wellness',
    'Sparsh Wellness',
    'HCG Wellness',
    'Rajiv Gandhi Wellness',
    'Tata Memorial Wellness',
    'Adyar Cancer Wellness',
    'Kidwai Wellness',
    'CMC Vellore Wellness',
    'CMC Ludhiana Wellness',
    'St Johns Wellness',
    'Bangalore Baptist Wellness',
    'St Martha\'s Wellness',
    'Bowring Wellness',
    'Victoria Wellness',
    'KEM Wellness',
    'Sion Wellness',
    'Nair Wellness',
    'Grant Medical Wellness',
    'JJ Wellness',
    'Cooper Wellness',
    'Bhatia Wellness',
    'Saifee Wellness',
    'Masina Wellness',
    'Holy Family Wellness',
    'St Elizabeth Wellness',
    'Holy Spirit Wellness',
    'PD Hinduja Wellness',
    'Apollo Pharmacy Online',
    'MedPlus Online',
    'Netmeds Online',
    'PharmEasy Online',
    '1mg Online',
    'Wellness Forever Online',
    'Guardian Pharmacy Online',
    'Trust Pharmacy Online',
    'Medlife Online',
    'Practo Online',
    'Fortis Healthcare Online',
    'Max Healthcare Online',
    'Manipal Hospitals Online',
    'Narayana Health Online',
    'Apollo Hospitals Online',
    'AIIMS Online',
    'Medanta Online',
    'Kokilaben Hospital Online',
    'Lilavati Hospital Online',
    'Hinduja Hospital Online',
    'Breach Candy Hospital Online',
    'Jaslok Hospital Online',
    'Nanavati Hospital Online',
    'Wockhardt Hospitals Online',
    'Columbia Asia Online',
    'Cloudnine Hospitals Online',
    'Motherhood Hospitals Online',
    'Rainbow Hospitals Online',
    'Aster DM Healthcare Online',
    'KIMS Hospitals Online',
    'Yashoda Hospitals Online',
    'Continental Hospitals Online',
    'Care Hospitals Online',
    'Global Hospitals Online',
    'Gleneagles Global Online',
    'Sakra World Hospital Online',
    'Sparsh Hospital Online',
    'HCG Oncology Online',
    'Rajiv Gandhi Cancer Institute Online',
    'Tata Memorial Hospital Online',
    'Adyar Cancer Institute Online',
    'Kidwai Memorial Online',
    'CMC Vellore Online',
    'CMC Ludhiana Online',
    'St Johns Hospital Online',
    'Bangalore Baptist Hospital Online',
    'St Martha\'s Hospital Online',
    'Bowring Hospital Online',
    'Victoria Hospital Online',
    'KEM Hospital Online',
    'Sion Hospital Online',
    'Nair Hospital Online',
    'Grant Medical College Online',
    'JJ Hospital Online',
    'Cooper Hospital Online',
    'Bhatia Hospital Online',
    'Saifee Hospital Online',
    'Masina Hospital Online',
    'Holy Family Hospital Online',
    'St Elizabeth Hospital Online',
    'Holy Spirit Hospital Online',
    'PD Hinduja Hospital Online',
  ],
  'HEALTH',
  62,
);

/** Regional outlet expansion — unique slugs for coverage depth without duplicating flagship brands. */
function regionalOutlets(
  brands: string[],
  cities: string[],
  category: string,
): MerchantCatalogDef[] {
  const rows: MerchantCatalogDef[] = [];
  for (const brand of brands) {
    for (const city of cities) {
      const name = `${brand} ${city}`;
      rows.push(
        m(name, category, {
          brandName: brand,
          parentBrand: brand,
          tags: ['regional-outlet', category.toLowerCase()],
          popularityScore: 20,
        }),
      );
    }
  }
  return rows;
}

const regional = [
  ...regionalOutlets(
    ['DMart', 'Reliance Smart', 'More', 'Spencer\'s', 'Big Bazaar'],
    ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad'],
    'GROCERY',
  ),
  ...regionalOutlets(
    ['Shell', 'Indian Oil', 'BPCL', 'HPCL'],
    ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad'],
    'FUEL',
  ),
  ...regionalOutlets(
    ['PVR', 'INOX', 'Cinepolis'],
    ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad'],
    'ENTERTAINMENT',
  ),
];

const allDefs = [
  ...flagship,
  ...shop,
  ...dining,
  ...grocery,
  ...travel,
  ...fuel,
  ...entertainment,
  ...utilities,
  ...health,
  ...regional,
];

/** Deduplicate by slug — first entry wins (flagship metadata preserved). */
export function buildMerchantCatalog(): MerchantCatalogDef[] {
  const seen = new Set<string>();
  const result: MerchantCatalogDef[] = [];
  for (const def of allDefs) {
    if (seen.has(def.slug)) continue;
    seen.add(def.slug);
    result.push(def);
  }
  return result;
}

export const MERCHANT_CATALOG = buildMerchantCatalog();

export const STANDARD_MCC_MAPPINGS = [
  { mccCode: '5411', categoryCode: 'GROCERY', description: 'Grocery stores, supermarkets' },
  { mccCode: '5812', categoryCode: 'DINING', description: 'Restaurants' },
  { mccCode: '5814', categoryCode: 'DINING', description: 'Fast food restaurants' },
  { mccCode: '5541', categoryCode: 'FUEL', description: 'Service stations (with or without ancillary services)' },
  { mccCode: '5542', categoryCode: 'FUEL', description: 'Automated fuel dispensers' },
  { mccCode: '4511', categoryCode: 'TRAVEL', description: 'Airlines, air carriers' },
  { mccCode: '7011', categoryCode: 'TRAVEL', description: 'Hotels, motels, resorts' },
  { mccCode: '4121', categoryCode: 'TRAVEL', description: 'Taxicabs and limousines' },
  { mccCode: '4112', categoryCode: 'TRAVEL', description: 'Passenger railways' },
  { mccCode: '5732', categoryCode: 'SHOP', description: 'Electronics stores' },
  { mccCode: '5311', categoryCode: 'SHOP', description: 'Department stores' },
  { mccCode: '5651', categoryCode: 'SHOP', description: 'Family clothing stores' },
  { mccCode: '5912', categoryCode: 'HEALTH', description: 'Drug stores and pharmacies' },
  { mccCode: '8011', categoryCode: 'HEALTH', description: 'Doctors and physicians' },
  { mccCode: '8062', categoryCode: 'HEALTH', description: 'Hospitals' },
  { mccCode: '4899', categoryCode: 'UTILITIES', description: 'Cable and other pay television services' },
  { mccCode: '4814', categoryCode: 'UTILITIES', description: 'Telecommunication services' },
  { mccCode: '4816', categoryCode: 'UTILITIES', description: 'Computer network services' },
  { mccCode: '7832', categoryCode: 'ENTERTAINMENT', description: 'Motion picture theaters' },
  { mccCode: '7922', categoryCode: 'ENTERTAINMENT', description: 'Theatrical producers and ticket agencies' },
  { mccCode: '5815', categoryCode: 'ENTERTAINMENT', description: 'Digital goods — media, books, movies, music' },
  { mccCode: '5999', categoryCode: 'SHOP', description: 'Miscellaneous and specialty retail stores' },
] as const;
